name: CI
on:
  push:
    branches: [ master ]
    tags: [ '*' ]
  pull_request:
    branches: [ '*' ]

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    if: (github.event.action != 'closed' || github.event.pull_request.merged == true)
    name: Build, test, and lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: clippy
      - name: Install cargo-nextest
        uses: taiki-e/install-action@nextest

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: nextest
          args: run

      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
